[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[BASE]
source = "container"
container = "library/alpine"
include_regex = "\\d+\\.\\d+\\.?\\d?"

[CONFD]
source = "github"
github = "kelseyhightower/confd"
use_max_tag = true
prefix = "v"
